import "./globals.css";
import "ui/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.Layout = ({ children }) => {
  return (
    <html>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
